/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 19-feb-2022 22:10:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS aud.error_iderror_seq
;

DROP SEQUENCE IF EXISTS aud.trace_idtrace_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS aud."Error" CASCADE
;

DROP TABLE IF EXISTS aud."LogLevel" CASCADE
;

DROP TABLE IF EXISTS aud."Trace" CASCADE
;


/* Create Tables */


CREATE TABLE aud."Error"
(
	"IdError" bigint NOT NULL   DEFAULT NEXTVAL(('aud."error_iderror_seq"'::text)::regclass),
	"Created" timestamp without time zone NOT NULL,
	"IdLogLevel" integer NULL,
	"Level" varchar(63) NULL,
	"CallerMethodFullName" varchar(127) NULL,
	"Message" text NULL,
	"Exception" text NULL,
	"Detail" text NULL,
	"SqlStatement" jsonb NULL,
	"IdUser" integer NULL,
	"ClientIp" varchar(63) NULL,
	"Environment" varchar(127) NULL,
	"ClientAgent" varchar(255) NULL,
	"ExceptionMessage" text NULL,
	"RequestPath" varchar(255) NULL,
	"RequestId" varchar(63) NULL,
	"RequestMethod" varchar(31) NULL,
	"MachineName" varchar(127) NULL,
	"ProcesId" varchar(63) NULL,
	"ThreadId" varchar(63) NULL
)
;

CREATE TABLE aud."LogLevel"
(
	"IdLogLevel" integer NOT NULL,
	"LogLevel" varchar(63) NULL,
	"ValidTo" timestamp without time zone NULL
)
;


CREATE TABLE aud."Trace"
(
	"IdTrace" bigint NOT NULL   DEFAULT NEXTVAL(('aud."trace_idtrace_seq"'::text)::regclass),
	"Created" timestamp without time zone NOT NULL,
	"IdLogLevel" integer NULL,
	"Level" varchar(63) NULL,
	"CallerMethodFullName" varchar(127) NULL,
	"Message" text NULL,
	"IdUser" integer NULL,
	"ClientIp" varchar(63) NULL,
	"ClientAgent" varchar(255) NULL,
	"RequestPath" varchar(255) NULL,
	"RequestId" varchar(63) NULL,
	"RequestMethod" varchar(31) NULL,
	"MachineName" varchar(127) NULL,
	"ProcesId" varchar(63) NULL,
	"ThreadId" varchar(63) NULL
)
;


/* Create Primary Keys, Indexes, Uniques, Checks */


ALTER TABLE aud."Error" ADD CONSTRAINT "PK_Error"
	PRIMARY KEY ("IdError")
;

CREATE INDEX "IXFK_Error_LogLevel" ON aud."Error" ("IdLogLevel" ASC)
;

ALTER TABLE aud."LogLevel" ADD CONSTRAINT "PK_LogLevel"
	PRIMARY KEY ("IdLogLevel")
;


ALTER TABLE aud."Trace" ADD CONSTRAINT "PK_Trace"
	PRIMARY KEY ("IdTrace")
;

CREATE INDEX "IXFK_Trace_LogLevel" ON aud."Trace" ("IdLogLevel" ASC)
;

/* Create Foreign Key Constraints */
ALTER TABLE aud."Error" ADD CONSTRAINT "FK_Error_LogLevel"
	FOREIGN KEY ("IdLogLevel") REFERENCES aud."LogLevel" ("IdLogLevel") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE aud."Trace" ADD CONSTRAINT "FK_Trace_LogLevel"
	FOREIGN KEY ("IdLogLevel") REFERENCES aud."LogLevel" ("IdLogLevel") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE aud.error_iderror_seq INCREMENT 1 START 1
;

CREATE SEQUENCE aud.trace_idtrace_seq INCREMENT 1 START 1
;
